# Generated by Django 4.1.2 on 2022-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortName', models.CharField(max_length=20)),
                ('ingredients', models.TextField()),
                ('currentPrice', models.FloatField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('is_ready', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfType', models.CharField(max_length=50)),
            ],
        ),
    ]
