# Generated by Django 4.1.2 on 2022-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты для заказа'},
        ),
        migrations.AlterModelOptions(
            name='typeofproduct',
            options={'ordering': ['nameOfType'], 'verbose_name': 'Тип еды', 'verbose_name_plural': 'Типы еды'},
        ),
        migrations.AlterField(
            model_name='pizza',
            name='currentPrice',
            field=models.FloatField(verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Список ингредиентов'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='is_ready',
            field=models.BooleanField(default=True, verbose_name='Готовность для продажи'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='shortName',
            field=models.CharField(max_length=20, verbose_name='Краткое наименование продукта'),
        ),
    ]
