# Generated by Django 4.1.2 on 2022-10-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0002_alter_pizza_options_alter_typeofproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='type_product',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='pizza_shop.typeofproduct', verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='nameOfType',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
