# Generated by Django 4.1.2 on 2022-10-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0004_buyers_alter_typeofproduct_nameoftype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий покупателя')),
                ('buyersname', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='pizza_shop.buyers', verbose_name='Имя покупателя')),
                ('product', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='pizza_shop.pizza', verbose_name='Наменование продукта')),
            ],
            options={
                'verbose_name': 'Отзыв (комментарий)',
                'verbose_name_plural': 'Отзывы (комментарии)',
                'ordering': ['product'],
            },
        ),
    ]
