# Generated by Django 4.1.2 on 2022-10-30 18:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0005_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyers',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес для доставки'),
        ),
        migrations.AddField(
            model_name='buyers',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Телефон покупателя'),
        ),
    ]
