# Generated by Django 4.1.2 on 2022-10-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0007_pizza_slug_alter_pizza_currentprice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
