# Generated by Django 4.1.2 on 2022-11-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0008_typeofproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='buyers',
            field=models.CharField(db_index=True, default='', max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
