# Generated by Django 4.1.2 on 2022-11-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0014_alter_typeofproduct_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks',
            old_name='buyers',
            new_name='buyer',
        ),
    ]
