# Generated by Django 4.1.2 on 2022-11-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0015_rename_buyers_feedbacks_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='buyersname',
        ),
    ]
