# Generated by Django 4.1.2 on 2022-11-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0016_remove_feedbacks_buyersname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='buyer',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='comment',
            field=models.CharField(max_length=250, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pizza_shop.pizza', verbose_name='Наменование продукта'),
        ),
    ]
